<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common.Exception\Common.Exception.csproj" />
      <ProjectReference Include="..\Common.Models\Common.Models.csproj" />
      <ProjectReference Include="..\Identity.Persistence\Identity.Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.13" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.13" />
    </ItemGroup>

</Project>
