<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common.Models\Common.Models.csproj" />
      <ProjectReference Include="..\Media.Persistence\Media.Persistence.csproj" />
      <ProjectReference Include="..\ServiceLayer\ServiceLayer.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.13" />
    </ItemGroup>

</Project>
